import { richText, type RichBlock } from './richText'

/** Real editorial content for the 10 practical guides (brief section 16). */
export type ResourceSeed = {
  slug: string
  title: string
  category: 'guide' | 'file-prep' | 'materials' | 'trends' | 'use-case'
  introduction: string
  body: ReturnType<typeof richText>
  seo: { metaTitle: string; metaDescription: string }
  status: 'review' | 'draft'
}

export const RESOURCES: ResourceSeed[] = [
  {
    slug: 'preparer-fichier-impression',
    title: 'Comment préparer un fichier pour l’impression',
    category: 'file-prep',
    introduction:
      'Un fichier peut paraître correct à l’écran et contenir pourtant des erreurs de format, de résolution, de couleur ou de coupe. La préparation consiste à vérifier ces points avant la validation finale.',
    body: richText([
      { h2: '1. Travaillez au format final' },
      { p: 'Composez directement aux dimensions finales du produit. Pour les formats ou structures particulières (packaging, découpe), utilisez uniquement le gabarit validé pour la configuration retenue — jamais une reconstitution approximative.' },
      { h2: '2. Ajoutez le fond perdu demandé' },
      { p: 'Le fond perdu prolonge les images et aplats au-delà de la ligne de coupe. Sa valeur exacte dépend du produit et du gabarit fourni.' },
      { h2: '3. Gardez les éléments importants à distance de la coupe' },
      { p: 'Prévoyez une zone de sécurité pour les textes, logos, numéros et informations importantes. Une zone dédiée doit aussi être respectée autour des plis, reliures, œillets ou perforations.' },
      { h2: '4. Vérifiez les images' },
      { ul: ['Dimensions réelles', 'Résolution effective', 'Netteté', 'Droits d’utilisation', 'Absence de compression excessive', 'Cadrage après fond perdu'] },
      { h2: '5. Préparez les couleurs pour l’impression' },
      { p: 'Les écrans affichent en RVB, les procédés d’impression travaillent en CMJN ou en tons directs. Utilisez le profil colorimétrique demandé pour la production.' },
      { h2: '6. Gérez les polices' },
      { p: 'Incorporez ou vectorisez les polices selon les instructions fournies, puis vérifiez accents, numéros, ligatures, graisses et sauts de ligne après export.' },
      { h2: '7. Contrôlez les noirs' },
      { p: 'Un petit texte noir et un grand aplat noir n’utilisent pas la même construction colorimétrique. Suivez les recommandations fournies pour éviter un flou, un maculage ou un rendu délavé.' },
      { h2: '8. Exportez dans le format demandé' },
      { p: 'Les réglages d’export PDF doivent correspondre au flux de production. Conservez le fichier source et les éléments liés.' },
      { h2: 'Checklist finale' },
      { ul: ['Format final vérifié', 'Fond perdu présent', 'Zone de sécurité respectée', 'Images nettes', 'Couleurs préparées', 'Polices correctes', 'Pages dans le bon ordre', 'Surimpressions contrôlées', 'Tracé de découpe séparé si nécessaire', 'PDF relu après export'] },
    ] satisfies RichBlock[]),
    seo: {
      metaTitle: 'Comment préparer un fichier pour l’impression | Printcom',
      metaDescription: 'Format, fond perdu, résolution, couleurs, polices et export PDF : vérifiez les points essentiels avant d’envoyer un fichier à imprimer.',
    },
    status: 'review',
  },
  {
    slug: 'comprendre-fond-perdu',
    title: 'Comprendre le fond perdu',
    category: 'file-prep',
    introduction:
      'Le fond perdu est une extension du visuel au-delà du format final. Il concerne les images, couleurs et formes qui doivent atteindre le bord du produit.',
    body: richText([
      { h2: 'Pourquoi existe-t-il ?' },
      { p: 'La coupe d’un imprimé n’est jamais parfaitement exacte. Le fond perdu agit comme une marge de sécurité visuelle pour que le bord reste couvert malgré une légère tolérance de coupe.' },
      { h2: 'Ce qui doit dépasser' },
      { ul: ['Photographies qui touchent le bord', 'Aplats de couleur', 'Motifs', 'Formes qui touchent le bord', 'Fonds de page'] },
      { p: 'Les textes et logos, à l’inverse, ne doivent jamais s’étendre dans le fond perdu — ils doivent rester dans la zone de sécurité.' },
      { h2: 'Trois lignes à distinguer' },
      { ul: ['Ligne de fond perdu : limite externe du fichier', 'Ligne de coupe : format final théorique', 'Zone de sécurité : espace intérieur pour les éléments importants'] },
      { h2: 'Produits qui demandent une attention particulière' },
      { ul: ['Cartes avec coins arrondis', 'Dépliants', 'Brochures', 'Chemises à rabats', 'Boîtes et étuis', 'Stickers découpés', 'Supports avec œillets', 'Produits reliés'] },
      { h2: 'Erreurs fréquentes' },
      { ul: ['Ajouter un cadre trop proche du bord', 'Étirer tout le fichier au lieu de prolonger le fond', 'Placer du texte dans le fond perdu', 'Utiliser une capture d’écran du gabarit', 'Retirer des repères techniques utiles', 'Oublier les zones de pli ou de collage'] },
      { h2: 'Règle de mise en œuvre' },
      { p: 'Il n’existe pas de valeur universelle de fond perdu : utilisez celle du gabarit fourni ou celle confirmée pour votre produit.' },
    ] satisfies RichBlock[]),
    seo: {
      metaTitle: 'Fond perdu en impression : définition et préparation | Printcom',
      metaDescription: 'Comprenez pourquoi le fond perdu est nécessaire et comment prolonger les images et aplats au-delà de la ligne de coupe.',
    },
    status: 'review',
  },
  {
    slug: 'resolution-image-impression',
    title: 'Quelle résolution utiliser ?',
    category: 'file-prep',
    introduction: 'Une image peut paraître nette à l’écran et devenir floue une fois imprimée à une taille différente.',
    body: richText([
      { h2: 'Résolution native et résolution effective' },
      { p: 'La netteté d’une image imprimée dépend de sa résolution effective à la taille finale, pas seulement de sa résolution native.' },
      { h2: 'La distance de lecture change le besoin' },
      { p: 'Un document tenu en main et une bâche vue à plusieurs mètres n’ont pas les mêmes exigences de définition.' },
      { h2: 'Ce qu’il faut vérifier' },
      { ul: ['Taille en pixels', 'Dimensions finales', 'Facteur d’agrandissement', 'Netteté du fichier source', 'Compression', 'Artefacts', 'Distance de lecture', 'Support final'] },
      { h2: 'Ce que l’interpolation ne peut pas faire' },
      { p: 'Agrandir artificiellement une image ne restitue pas les détails absents du fichier source.' },
      { h2: 'Logos et pictogrammes' },
      { p: 'Utilisez des fichiers vectoriels lorsque c’est possible : ils restent nets à toute taille.' },
      { h2: 'Grand format' },
      { p: 'Un visuel grand format peut être travaillé à échelle réduite si cela est clairement documenté et compatible avec la production.' },
      { h2: 'Avant l’envoi' },
      { p: 'Exportez une vue de contrôle et zoomez sur les visages, petits textes intégrés à l’image et détails produit.' },
    ] satisfies RichBlock[]),
    seo: {
      metaTitle: 'Quelle résolution pour une impression nette ? | Printcom',
      metaDescription: 'Comprenez la résolution effective, la taille finale et la distance de lecture pour éviter les images floues à l’impression.',
    },
    status: 'review',
  },
  {
    slug: 'rvb-cmjn-impression',
    title: 'RVB ou CMJN ?',
    category: 'file-prep',
    introduction: 'L’écran émet de la lumière. Le papier la réfléchit. C’est pourquoi une couleur peut changer entre les deux.',
    body: richText([
      { h2: 'Pourquoi certaines couleurs changent' },
      { p: 'Un écran compose la couleur par émission lumineuse ; l’impression la compose par réflexion de la lumière sur l’encre et le support.' },
      { h2: 'Quand convertir' },
      { p: 'La conversion RVB vers CMJN (ou vers un ton direct) doit être effectuée avec le profil colorimétrique correspondant au procédé retenu.' },
      { h2: 'Points à contrôler' },
      { ul: ['Profil incorporé', 'Couleurs hors gamut', 'Noirs', 'Gris neutres', 'Images provenant de sources différentes', 'Tons directs', 'Transparences', 'Surimpressions'] },
      { h2: 'Tons directs' },
      { p: 'Les références Pantone peuvent être envisagées selon disponibilité — à confirmer pour chaque projet.' },
      { h2: 'Le rôle de l’épreuve' },
      { p: 'Une épreuve constitue une référence dans un contexte défini ; elle ne remplace pas un écran non calibré.' },
      { h2: 'Recommandation' },
      { p: 'Conservez la version source, documentez les profils utilisés, et vérifiez le PDF final. Demandez le niveau de validation adapté pour les projets sensibles à la couleur.' },
    ] satisfies RichBlock[]),
    seo: {
      metaTitle: 'RVB ou CMJN : préparer les couleurs pour l’impression | Printcom',
      metaDescription: 'Découvrez la différence entre RVB et CMJN, les limites de conversion et les vérifications utiles avant l’impression.',
    },
    status: 'review',
  },
  {
    slug: 'choisir-grammage-papier',
    title: 'Comment choisir un grammage ?',
    category: 'materials',
    introduction: 'Le grammage influence la tenue, le toucher, le pliage et l’usage. Un poids plus élevé n’est pas toujours le plus adapté.',
    body: richText([
      { h2: 'Commencez par la fonction' },
      { p: 'Le grammage doit être choisi en fonction de l’usage réel du support, pas d’une préférence esthétique isolée.' },
      { h2: 'Les propriétés à comparer' },
      { ul: ['Grammage', 'Épaisseur', 'Rigidité', 'Opacité', 'Blancheur', 'Texture', 'Couchage', 'Sens de la fibre', 'Compatibilité avec le pli', 'Compatibilité avec la finition'] },
      { h2: 'Même grammage, sensation différente' },
      { p: 'Deux papiers du même grammage peuvent avoir une épaisseur ou une rigidité perçue très différente selon leur fabrication.' },
      { h2: 'Pliage et rainage' },
      { p: 'Au-delà d’un certain grammage, un rainage devient nécessaire pour obtenir un pli net.' },
      { h2: 'Expédition et manipulation' },
      { p: 'Le grammage a aussi un impact sur le poids total, le coût d’expédition et la résistance à la manipulation répétée.' },
      { h2: 'Choix responsable' },
      { p: 'N’appelez pas un papier « écologique » sur la seule base de sa couleur ou de son aspect : vérifiez la composition, les certifications et la disponibilité réelle.' },
    ] satisfies RichBlock[]),
    seo: {
      metaTitle: 'Comment choisir le grammage du papier ? | Printcom',
      metaDescription: 'Le grammage influence la tenue, le toucher, le pliage et l’usage. Découvrez les questions à poser avant de choisir un papier.',
    },
    status: 'review',
  },
  {
    slug: 'offset-ou-numerique',
    title: 'Offset ou numérique ?',
    category: 'guide',
    introduction: 'Deux procédés, deux logiques. Le choix dépend du projet, pas d’une préférence a priori.',
    body: richText([
      { h2: 'L’offset peut être envisagé lorsque' },
      { ul: ['Le tirage est moyen ou important', 'La quantité est stable', 'Le support est standard', 'Le nombre de couleurs est défini', 'La reproduction doit rester constante sur tout le tirage'] },
      { h2: 'Le numérique peut être envisagé lorsque' },
      { ul: ['La série est courte', 'Le contenu varie d’un exemplaire à l’autre', 'Le délai est court', 'Une personnalisation est nécessaire', 'Le test ou le prototypage précède un tirage plus large'] },
      { h2: 'Les critères qui comptent' },
      { ul: ['Quantité', 'Nombre de versions', 'Personnalisation', 'Format', 'Papier ou matériau', 'Couleur', 'Finition', 'Calendrier', 'Budget', 'Disponibilité réelle des équipements'] },
      { h2: 'Ne choisissez pas sur un seul critère' },
      { p: 'La quantité seule ne suffit pas à trancher : la combinaison des critères ci-dessus oriente le procédé le plus adapté.' },
      { h2: 'La bonne question' },
      { p: 'Plutôt que de demander « offset ou numérique ? », décrivez le produit, l’usage, la quantité, les versions et la date souhaitée : le procédé peut ensuite être étudié.' },
    ] satisfies RichBlock[]),
    seo: {
      metaTitle: 'Impression offset ou numérique : comment choisir ? | Printcom',
      metaDescription: 'Quantité, personnalisation, support, couleur et délai : comparez les critères qui orientent vers l’offset ou le numérique.',
    },
    status: 'review',
  },
  {
    slug: 'choisir-finition-impression',
    title: 'Comment choisir une finition ?',
    category: 'materials',
    introduction: 'Une finition doit avoir une fonction : protéger, guider le regard, ajouter du toucher ou donner une forme.',
    body: richText([
      { h2: 'Protéger' },
      { p: 'Un pelliculage ou un vernis peut limiter l’usure sur un support très manipulé.' },
      { h2: 'Guider le regard' },
      { p: 'Un vernis sélectif ou un contraste de brillance peut mettre en valeur une zone précise sans surcharger l’ensemble.' },
      { h2: 'Ajouter du toucher' },
      { p: 'Un soft touch, un gaufrage ou un texturé transforme la manipulation du support en expérience.' },
      { h2: 'Donner la forme' },
      { p: 'La découpe et le façonnage déterminent la structure finale du produit, au-delà du seul rendu visuel.' },
      { h2: 'Questions à poser' },
      { ul: ['Quel est l’usage réel du support ?', 'Sera-t-il manipulé souvent ?', 'Doit-il résister à l’humidité ou à la lumière ?', 'Une zone doit-elle être mise en avant ?', 'La finition est-elle compatible avec le support retenu ?', 'La finition est-elle compatible avec les autres options choisies ?'] },
      { h2: 'Principe de retenue' },
      { p: 'Une finition premium n’est pas celle qui cumule le plus d’effets. C’est celle qui rend l’intention plus claire.' },
    ] satisfies RichBlock[]),
    seo: {
      metaTitle: 'Comment choisir une finition d’impression ? | Printcom',
      metaDescription: 'Protection, toucher, reflet, relief ou forme : choisissez une finition selon l’usage du produit et le support retenu.',
    },
    status: 'review',
  },
  {
    slug: 'preparer-fichier-decoupe',
    title: 'Préparer un fichier de découpe',
    category: 'file-prep',
    introduction: 'La forme d’un produit découpé doit être aussi précise que son visuel.',
    body: richText([
      { h2: 'Utilisez un tracé vectoriel' },
      { p: 'Le tracé de découpe doit être vectoriel, jamais une image bitmap approximative.' },
      { h2: 'Séparez la technique du visuel' },
      { p: 'Placez le tracé sur un calque nommé, avec une couleur technique (souvent un ton direct dédié) qui ne doit jamais apparaître dans le visuel imprimé.' },
      { h2: 'Prévoyez le fond perdu' },
      { p: 'Comme pour une coupe droite, les éléments qui touchent le bord de la forme doivent être prolongés au-delà de la découpe.' },
      { h2: 'Évitez les formes trop fragiles' },
      { p: 'Des pointes fines ou des zones trop étroites peuvent ne pas résister à la découpe ou à la manipulation.' },
      { h2: 'Packaging' },
      { p: 'Distinguez clairement, sur des calques séparés : la coupe, le rainage, la perforation, la zone de collage, le sens de montage, la face intérieure et la face extérieure. Ne modifiez jamais un gabarit structurel sans validation.' },
      { h2: 'Vérification finale' },
      { p: 'Contrôlez que le tracé ferme correctement, sans point dupliqué ni segment ouvert, avant l’envoi.' },
    ] satisfies RichBlock[]),
    seo: {
      metaTitle: 'Comment préparer un fichier de découpe ? | Printcom',
      metaDescription: 'Trace vectorielle, couleur technique, fond perdu et zones de sécurité : préparez une forme de découpe exploitable.',
    },
    status: 'review',
  },
  {
    slug: 'valider-bon-a-tirer',
    title: 'Comment valider un bon à tirer ?',
    category: 'guide',
    introduction: 'La version validée devient la référence de production : elle mérite une relecture complète.',
    body: richText([
      { h2: 'Vérifiez le contenu' },
      { ul: ['Orthographe', 'Noms propres', 'Numéros', 'Coordonnées', 'Dates', 'Prix ou références fournis', 'Mentions', 'Langues', 'QR codes', 'Codes-barres'] },
      { h2: 'Vérifiez la structure' },
      { ul: ['Format', 'Orientation', 'Nombre de pages', 'Ordre des pages', 'Plis', 'Recto-verso', 'Pagination', 'Sens de lecture', 'Emplacement des découpes'] },
      { h2: 'Vérifiez les images' },
      { ul: ['Bonne version', 'Cadrage', 'Netteté', 'Droits', 'Absence de contenu masqué', 'Cohérence avec la légende'] },
      { h2: 'Vérifiez les options' },
      { ul: ['Papier', 'Grammage', 'Couleur', 'Finition', 'Reliure', 'Quantité', 'Conditionnement', 'Destinations'] },
      { h2: 'Comprenez la portée de la validation' },
      { p: 'Un BAT visualisé à l’écran ne permet pas toujours de juger le toucher du papier ou la couleur réellement imprimée.' },
      { h2: 'Après validation' },
      { p: 'Conservez la référence, la date et le nom du validateur. Toute modification ultérieure nécessite une nouvelle version clairement identifiée.' },
    ] satisfies RichBlock[]),
    seo: {
      metaTitle: 'Bon à tirer : les points à vérifier avant validation | Printcom',
      metaDescription: 'Texte, format, pages, images, couleurs et finitions : utilisez cette checklist avant de valider un bon à tirer.',
    },
    status: 'review',
  },
  {
    slug: 'formats-fichiers-acceptes',
    title: 'Formats de fichiers acceptés',
    category: 'file-prep',
    introduction:
      'Cette page décrit la structure recommandée pour transmettre un fichier. Les formats réellement acceptés par Printcom doivent être configurés dans l’administration avant publication.',
    body: richText([
      { h2: 'Structure recommandée' },
      { ul: ['PDF final', 'Fichier source', 'Images liées', 'Polices, si la licence en autorise la transmission', 'Fichier vectoriel', 'Tableur ou base, si applicable'] },
      { h2: 'Informations à joindre' },
      { ul: ['Produit', 'Format final', 'Quantité', 'Version', 'Langue', 'Finition', 'Date souhaitée', 'Instructions particulières'] },
      { h2: 'Fichiers à éviter' },
      { ul: ['Captures d’écran', 'Images reçues par messagerie', 'PDF non relu', 'Logo copié depuis un site', 'Document bureautique non vérifié', 'Lien cloud sans autorisation d’accès'] },
      { p: 'Remplacer cette page par les formats, tailles maximales et méthodes de transfert réellement confirmés par Printcom avant de la publier.' },
    ] satisfies RichBlock[]),
    seo: {
      metaTitle: 'Formats de fichiers pour l’impression | Printcom',
      metaDescription: 'Découvrez les formats de fichiers à transmettre selon votre projet et les éléments à joindre pour faciliter le contrôle.',
    },
    status: 'draft',
  },
]
